[package]
name = "fbec"
version = "0.1.0"
edition = "2024"
authors = ["Panilux Team"]
description = "Fast Binary Encoding compiler for Rust"
license = "MIT"

[[bin]]
name = "fbec"
path = "src/main.rs"

[dependencies]
regex = "1"
